#SPDX-FileCopyrightText: 2025 Intevation GmbH
#SPDX-License-Identifier: AGPL-3.0-or-later
#

name: 'CSAF Advisory Provider'
description: 'Creates the CSAF documents to create a CSAF trusted provider'
author:

inputs:
  csaf_version:
    description: The version of the gocsaf/csaf tool suite
    default: 3.3.0
    required: false
  secvisogram_version:
    description: Version of the secvisogram validator service
    default: 2.0.7
    required: false
  publisher_category:
    description: The category of the CSAF Publisher
    default: vendor
    required: false
  publisher_name:
    description: Name of the CSAF Publisher
    required: true
  publisher_namespace:
    description: URL of the CSAF Publisher
    required: true
  publisher_issuing_authority:
    description: Description of the Issuing Authority of the CSAF Publisher
    required: true
  publisher_contact_details:
    description: Contact details of the CSAF Publisher
    required: true
  source_csaf_documents:
    description: Path to the CSAF source documents
    default: csaf_documents/
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.publisher_category }}
    - ${{ inputs.publisher_name }}
    - ${{ inputs.publisher_namespace }}
    - ${{ inputs.publisher_issuing_authority }}
    - ${{ inputs.publisher_contact_details }}
    - ${{ inputs.publisher_csaf_documents }}
