#SPDX-FileCopyrightText: 2025 Intevation GmbH
#SPDX-License-Identifier: AGPL-3.0-or-later
#
name: "CSAF Provider"
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  csaf:
    runs-on: ubuntu-24.04
    name: Create CSAF documents
    strategy:
      fail-fast: false

    steps:
    - name: Publish CSAF advisories
      uses: wagner-intevation/csaf-action@main
      with:
        publisher_name: Example Company
        publisher_namespace: https://example.com
        publisher_issuing_authority: "We at Example Company are responsible for publishing and maintaining Product Y."
        publisher_contact_details: "Example Company can be reached at contact_us@example.com or via our website at https://www.example.com/contact."
        source_csaf_documents: test/inputs/
